"""Add savings goals

Revision ID: 4c8c7660418d
Revises: 0002_add_budgets
Create Date: 2026-09-18 15:01:22.241894

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op



# revision identifiers, used by Alembic.
revision: str = '4c8c7660418d'
down_revision: str | None = '0002_add_budgets'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('savings_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('current_amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('target_date', sa.DATE(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_savings_goals_id'), 'savings_goals', ['id'], unique=False)
    op.create_index('ix_savings_goals_user', 'savings_goals', ['user_id'], unique=False)
    op.create_index(op.f('ix_savings_goals_user_id'), 'savings_goals', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_savings_goals_user_id'), table_name='savings_goals')
    op.drop_index('ix_savings_goals_user', table_name='savings_goals')
    op.drop_index(op.f('ix_savings_goals_id'), table_name='savings_goals')
    op.drop_table('savings_goals')
    # ### end Alembic commands ###
